extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "prettier"
  - "plugin:escompat/typescript"
rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-unused-vars":
    - "error"
    - argsIgnorePattern: "^_"
  "@typescript-eslint/camelcase": off
  "@typescript-eslint/unbound-method":
    - "error"
    - ignoreStatic: true

parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: 2018
  project:
    - ./tsconfig.json
    - ./typedoc-theme/tsconfig.json
  sourceType: "module"

root: true
