extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/strict-type-checked"
  - "prettier"
  - "plugin:escompat/typescript"
rules:
  "@typescript-eslint/unified-signatures": off
  "@typescript-eslint/no-unnecessary-condition": off

parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "escompat"
parserOptions:
  ecmaVersion: 2018
  project:
    - ./tsconfig.json
    - ./website/tsconfig.json
  sourceType: "module"

root: true
